version: '3.4'

services:    
  api:
    restart: always
    build: Api/.
    ports:
      - '5001:443'
    environment:
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_HTTPS_PORT: 8081
      ASPNETCORE_Kestrel__Certificates__Default__Password: sEcREtpaSsWord
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/httpscertificate.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - db
      
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: my_db
    volumes:
       - db-volume:/var/lib/postgresql/data
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  #mongo:
  #  image: mongo
  #  restart: always
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: root
  #    MONGO_INITDB_ROOT_PASSWORD: example
  #  ports:
  #    - '27017:27017'
  #  volumes:
  #    - mongo-volume:/data/db

volumes:
  db-volume:
  mongo-volume: